java -Xms2g -Xmx2g -XX:+UseParallelGC -cp .:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $* -b 60 setting/sapienza/path_Direct.txt
java -Xms2g -Xmx2g -XX:+UseParallelGC -cp .:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $* -b 60 setting/sapienza/path_Epidemic.txt
java -Xms2g -Xmx2g -XX:+UseParallelGC -cp .:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $* -b 60 setting/sapienza/path_Spray.txt
java -Xms2g -Xmx2g -XX:+UseParallelGC -cp .:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $* -b 60 setting/sapienza/path_FirstContact.txt
java -Xms2g -Xmx2g -XX:+UseParallelGC -cp .:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $* -b 60 setting/sapienza/path_Prophet.txt
java -Xms2g -Xmx2g -XX:+UseParallelGC -cp .:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $* -b 60 setting/sapienza/path_Fuzzy.txt
java -Xms2g -Xmx2g -XX:+UseParallelGC -cp .:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $* -b 60 setting/sapienza/path_MaxProp.txt
java -Xms2g -Xmx2g -XX:+UseParallelGC -cp .:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $* -b 60 setting/sapienza/path_Fad.txt
java -Xms2g -Xmx2g -XX:+UseParallelGC -cp .:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $* -b 60 setting/sapienza/path_Scar.txt
java -Xms2g -Xmx2g -XX:+UseParallelGC -cp .:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $* -b 60 setting/sapienza/path_Rapid.txt